### ISSUE TITLE
TODO lists

### ISSUE THREAD

**Issue by yangtcai** [yangtcai/Ensembl-Repeat-Identification#7]
- [ ] Deal with dataset formats
- [ ] Implement dataloader function
- [ ] Implement encode function, eg one hot
